# -*- coding: utf-8 -*-
# Deployment settings for words.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['F:/Marmalade/7.9/s3e/makefile_builder/mkb.py', 'f:/Users/Teal/Documents/Marmalade/words/words.mkb', '--buildenv=VC12X', '--default-buildenv=vc12x', '--msvc-project', '--deploy-only']
mkb = 'f:/Users/Teal/Documents/Marmalade/words/words.mkb'
mkf = ['f:\\marmalade\\7.9\\s3e\\s3e-default.mkf', 'f:\\marmalade\\7.9\\extensions\\s3eamazonads\\s3eamazonads.mkf', 'f:\\marmalade\\7.9\\modules\\iwutil\\iwutil.mkf', 'f:\\marmalade\\7.9\\modules\\third_party\\libjpeg\\libjpeg.mkf', 'f:\\marmalade\\7.9\\modules\\third_party\\libpng\\libpng.mkf', 'f:\\marmalade\\7.9\\modules\\third_party\\zlib\\zlib.mkf', 'f:\\marmalade\\7.9\\platform_libs\\android\\amazon-ads-android-sdk\\amazon-ads-android-sdk.mkf', 'f:\\marmalade\\7.9\\platform_libs\\iphone\\amazon-ads-ios-sdk\\amazon-ads-ios-sdk.mkf', 'f:\\marmalade\\7.9\\modules\\iw2dscenegraphcore\\iw2dscenegraphcore.mkf', 'f:\\marmalade\\7.9\\modules\\iw2dscenegraph\\iw2dscenegraph.mkf', 'f:\\marmalade\\7.9\\modules\\iw2d\\iw2d.mkf', 'f:\\marmalade\\7.9\\modules\\iwgx\\iwgx.mkf', 'f:\\marmalade\\7.9\\modules\\iwgl\\iwgl.mkf', 'f:\\marmalade\\7.9\\modules\\iwgeom\\iwgeom.mkf', 'f:\\marmalade\\7.9\\modules\\iwresmanager\\iwresmanager.mkf', 'f:\\marmalade\\7.9\\extensions\\pvrtextool\\pvrtextool.mkf', 'f:\\marmalade\\7.9\\modules\\iwgxfont\\iwgxfont.mkf', 'f:\\marmalade\\7.9\\modules\\third_party\\tiniconv\\tiniconv.mkf', 'f:\\marmalade\\7.9\\modules\\iwtween\\iwtween.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('f:/Users/Teal/Documents/Marmalade/words\data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'words'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'words'
    long_caption = 'words'
    version = [0, 0, 1]
    config = ['f:/Users/Teal/Documents/Marmalade/words/data/app.icf']
    data_dir = 'f:/Users/Teal/Documents/Marmalade/words/data'
    mkb_dir = 'f:/Users/Teal/Documents/Marmalade/words'
    iphone_link_lib = ['s3eAmazonAds']
    osx_ext_dll = ['f:/marmalade/7.9/extensions/pvrtextool/lib/osx/libPVRTexTool.dylib']
    wp81_extra_pri = []
    ws8_ext_capabilities = []
    ws8_ext_native_only_dll = []
    win10_ext_uap_capabilities = []
    win10_ext_native_dll = []
    ws81_ext_native_only_dll = []
    android_external_res = []
    win32_ext_dll = ['f:/marmalade/7.9/extensions/pvrtextool/lib/win32/PVRTexTool.dll']
    win10_ext_sdk_ref = []
    wp8_ext_capabilities = []
    ws8_extra_res = []
    ws81_ext_managed_dll = []
    iphone_link_libdir = ['f:/marmalade/7.9/extensions/s3eamazonads/lib/iphone']
    android_extra_application_manifest = ['f:/marmalade/7.9/extensions/s3eamazonads/source/android/ExtraAppManifests.xml']
    win10_extra_res = []
    ws8_ext_native_dll = []
    android_external_assets = []
    blackberry_extra_descriptor = []
    android_ext_target_sdk_version = [17]
    android_extra_manifest = []
    wp81_ext_sdk_ref = []
    iphone_link_libdirs = []
    wp81_ext_device_capabilities = []
    win10_ext_capabilities = []
    linux_ext_lib = []
    android_ext_min_sdk_version = [4]
    wp81_ext_native_only_dll = []
    ws8_ext_managed_dll = []
    ws8_ext_sdk_manifest_part = []
    ws8_ext_device_capabilities = []
    ws81_extra_pri = []
    android_external_jars = ['f:/marmalade/7.9/platform_libs/android/amazon-ads-android-sdk/third_party/lib/amazon-ads-5.5.149.jar', 'f:/marmalade/7.9/extensions/s3eamazonads/lib/android/s3eAmazonAds.jar']
    win8_winrt_extra_res = []
    wp81_ext_sdk_manifest_part = []
    wp81_extra_res = []
    wp81_ext_managed_dll = []
    wp81_ext_capabilities = []
    win10_ext_managed_dll = []
    iphone_extra_plist = []
    ws81_ext_sdk_manifest_part = []
    ws81_ext_device_capabilities = []
    android_supports_gl_texture = []
    ws8_ext_sdk_ref = []
    iphone_extra_string = []
    tizen_so = []
    wp8_ext_native_dll = []
    win10_ext_sdk_manifest_part = []
    win10_extra_pri = []
    win10_ext_device_capabilities = []
    win8_phone_extra_res = []
    win32_aux_dll = []
    win8_store_extra_res = []
    iphone_link_opts = ['-Ff:/marmalade/7.9/platform_libs/iphone/amazon-ads-ios-sdk/third_party/Ads -framework AmazonAd', '-weak_framework AdSupport -weak_framework CoreLocation -weak_framework SystemConfiguration', '-weak_framework CoreTelephony -weak_framework MediaPlayer', '-weak_framework EventKit -weak_framework EventKitUI']
    ws81_ext_sdk_ref = []
    wp8_extra_res = []
    ws81_ext_native_dll = []
    ws8_extra_pri = []
    wp8_ext_managed_dll = []
    android_extra_packages = []
    android_so = ['f:/marmalade/7.9/extensions/s3eamazonads/lib/android/libs3eAmazonAds.so']
    wp8_ext_sdk_ref = []
    osx_extra_res = []
    ws81_extra_res = []
    wp81_ext_native_dll = []
    ws81_ext_capabilities = []
    iphone_link_libs = []
    android_extra_strings = []
    target = {
         'mips' : {
                   'debug'   : r'f:/Users/Teal/Documents/Marmalade/words/build_words_vc12x/Debug_words_VC12X_gcc_mips/words.so',
                   'release' : r'f:/Users/Teal/Documents/Marmalade/words/build_words_vc12x/Release_words_VC12X_gcc_mips/words.so',
                 },
         'gcc_x86' : {
                   'debug'   : r'f:/Users/Teal/Documents/Marmalade/words/build_words_vc12x/Debug_words_VC12X_gcc_x86/words.so',
                   'release' : r'f:/Users/Teal/Documents/Marmalade/words/build_words_vc12x/Release_words_VC12X_gcc_x86/words.so',
                 },
         'gcc_x86_tizen' : {
                   'debug'   : r'f:/Users/Teal/Documents/Marmalade/words/build_words_vc12x/Debug_words_VC12X_gcc_x86_tizen/words.s86',
                   'release' : r'f:/Users/Teal/Documents/Marmalade/words/build_words_vc12x/Release_words_VC12X_gcc_x86_tizen/words.s86',
                 },
         'firefoxos' : {
                   'debug'   : r'f:/Users/Teal/Documents/Marmalade/words/build_words_vc12x/Debug_words_VC12X_firefoxos/words.js',
                   'release' : r'f:/Users/Teal/Documents/Marmalade/words/build_words_vc12x/Release_words_VC12X_firefoxos/words.js',
                 },
         'mips_gcc' : {
                   'debug'   : r'f:/Users/Teal/Documents/Marmalade/words/build_words_vc12x/Debug_words_VC12X_gcc_mips/words.so',
                   'release' : r'f:/Users/Teal/Documents/Marmalade/words/build_words_vc12x/Release_words_VC12X_gcc_mips/words.so',
                 },
         'arm_gcc' : {
                   'debug'   : r'f:/Users/Teal/Documents/Marmalade/words/build_words_vc12x/Debug_words_VC12X_gcc_arm/words.s3e',
                   'release' : r'f:/Users/Teal/Documents/Marmalade/words/build_words_vc12x/Release_words_VC12X_gcc_arm/words.s3e',
                 },
         'naclx86_64' : {
                   'debug'   : r'f:/Users/Teal/Documents/Marmalade/words/build_words_vc12x/Debug_words_VC12X_gcc_naclx86_64/words.so.s64',
                   'release' : r'f:/Users/Teal/Documents/Marmalade/words/build_words_vc12x/Release_words_VC12X_gcc_naclx86_64/words.so.s64',
                 },
         'aarch64_gcc' : {
                   'debug'   : r'f:/Users/Teal/Documents/Marmalade/words/build_words_vc12x/Debug_words_VC12X_gcc_aarch64/words.s3e',
                   'release' : r'f:/Users/Teal/Documents/Marmalade/words/build_words_vc12x/Release_words_VC12X_gcc_aarch64/words.s3e',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'f:/Users/Teal/Documents/Marmalade/words/build_words_vc12x/Debug_words_VC12X_gcc_x86_android/words.so',
                   'release' : r'f:/Users/Teal/Documents/Marmalade/words/build_words_vc12x/Release_words_VC12X_gcc_x86_android/words.so',
                 },
         'arm' : {
                   'debug'   : r'f:/Users/Teal/Documents/Marmalade/words/build_words_vc12x/Debug_words_VC12X_arm/words.s3e',
                   'release' : r'f:/Users/Teal/Documents/Marmalade/words/build_words_vc12x/Release_words_VC12X_arm/words.s3e',
                 },
         'x86' : {
                   'debug'   : r'f:/Users/Teal/Documents/Marmalade/words/build_words_vc12x/Debug_words_VC12X_x86/words.s86',
                   'release' : r'f:/Users/Teal/Documents/Marmalade/words/build_words_vc12x/Release_words_VC12X_x86/words.s86',
                 },
        }
    arm_arch = ''
    assets_original = assets
    assets = assets['Default']

default = DefaultConfig()
